image: node:latest

cache:
  paths:
    - node_modules/

deploy:
    stage: deploy
    script:
        - ls
        - git remote -v
        - git config -l
    artifacts:
        paths:
            - src
    tags: 
        - "react"
    rules: 
        - if: '$CI_COMMIT_BRANCH == "main"'
